### ISSUE TITLE
Which paper did this method come from?

### ISSUE THREAD

**Issue by KaiiZhang** [arsenyinfo/qudida#2]
Thanks for your great work! 
I think this pixel-level domain adaptation method may be useful in my research work. So I am curious whether this method comes from any specific paper, which will help me to cite and understand its theory.

**Comment by arsenyinfo** [comment]
Hi @KaiiZhang! 
Unfortunately, there was no paper or public benchmarks - just my experiments on private datasets. 

Feel free to send me an email to me@arseny.info if you think I can help you.
