### ISSUE TITLE
License

### ISSUE THREAD

**Issue by flix59** [arsenyinfo/qudida#4]
Running pip show qudida after a successful pip installation yields:

#!text
Name: qudida
Version: 0.0.4
Summary: QUick and DIrty Domain Adaptation
Home-page: https://github.com/arsenyinfo/qudida
Author: None
Author-email: None
License: UNKNOWN
Location: /opt/conda/lib/python3.7/site-packages
Requires: scikit-learn, typing-extensions, opencv-python-headless, numpy
Required-by: albumentations

As seen above, the "License" metadata field incorrectly states that it is UNKNOWN.
Since this repository has an MIT License it seems that something in the setup.py is missing. Most likely the licenses attribute in the call to setup() in setup.py

**Comment by vonschultz** [comment]
@arsenyinfo, how about a new release? A version 0.0.5, perhaps. Having the license metadata in the released version makes life easier for a certain category of users.
